apiVersion: v2
name: common
description: Function library for ferry133 charts
type: library
version: 4.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - ferry133
  - common
home: https://github.com/ferry133/library-charts/tree/main/stable/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
  - name: onedr0p
    email: devin.kray@gmail.com
  - name: dirtycajunrice
    email: nick@cajun.pro
